### ISSUE TITLE
bertxml

### ISSUE THREAD

**Issue by wangchichi1999** [XunGuangxu/CorNet#1]
Hi!
well job！
When we use BertXML or BertXMLCornet, do we still need to use Glove?

**Comment by XunGuangxu** [comment]
Hi, yes, in my experiments, GloVe embeddings are used as initializations for all models.

**Comment by wangchichi1999** [comment]
Got it! Thanks!
Sooooo why not Bert pretrained models?

**Comment by XunGuangxu** [comment]
Hi, because the structure of BertXML is different from Bert, so you can not directly use pretrained Bert to initialize the model. If you want to use pretrained Bert to initialize BertXML, you will need to be careful with the parameter alignment. Another reason we didn't use pretrained Bert is that we wanted the BertXML initialization method consistent with the other baselines.
